Repository camunda-cloud/camunda-cloud-docs, pull requests merged in 2020-06, with the labels that each got.

#32 Update screen shots
  docs/assets/cluster-details-create-client.png
  docs/assets/cluster-details-creating.png
  docs/assets/cluster-details-healthy.png
  docs/assets/cluster-details.png
  docs/assets/cluster-overview-empty.png
  docs/assets/cluster-overview-new-cluster-creating.png
  docs/assets/cluster-overview-new-cluster-healthy.png
  docs/assets/cluster-overview-new-cluster-unhealthy.png
  docs/assets/early-access-paid-request.png
  docs/assets/workflow-calling-webhook-site-service-task-properties-general.png
  docs/assets/workflow-calling-webhook-site-service-task-properties-headers.png
  docs/assets/workflow-calling-webhook-site-worker-variables.png
  docs/gettingstarted_camunda-cloud-console.md
  docs/zeebecluster_embedded-http-worker.md
Labels: size/M

#34 Tabbed design
  docs/assets/cluster-detail-clients.png
  docs/assets/cluster-details-client-details.png
  docs/assets/cluster-details-create-client.png
  docs/assets/cluster-details-creating.png
  docs/assets/cluster-details-healthy.png
  docs/assets/cluster-details.png
  docs/assets/cluster-overview-empty.png
  docs/assets/cluster-overview-new-cluster-creating.png
  docs/assets/cluster-overview-new-cluster-healthy.png
  docs/assets/cluster-overview-new-cluster-unhealthy.png
  docs/assets/contact-feedback-and-support.png
  docs/assets/early-access-paid-request.png
  docs/assets/early-access-reserved-clusters-edit.png
  docs/assets/early-access-reserved-clusters-overview.png
  docs/gettingstarted_quick-start.md
Labels: size/S

#33 Improve getting started quick start advanced
  docs/assets/zeebe-modeler-advanced-process-id.png
  docs/assets/zeebe-modeler-advanced-sequence-flows.png
  docs/gettingstarted_quick-start-advanced.md
Labels: lgtm, size/M

#35 Add Node.js Getting Started Guide
  docs/assets/getting-started-node-thumbnail.jpg
  docs/connectzeebe_node-client.md
Labels: size/L

#36 Add missing images
  .gitignore
  docs/assets/gettingstarted_first-model.png
  docs/assets/gettingstarted_second-model.png
  docs/connectzeebe_node-client.md
Labels: lgtm, size/XS
