Repository camunda-cloud/camunda-cloud-docs, pull requests merged in 2020-07, with the labels that each got.

#37 updated screenshots for console release 0.1.88
  docs/assets/cluster-detail-clients.png
  docs/assets/cluster-details-client-details.png
  docs/assets/cluster-details-create-client.png
  docs/assets/cluster-overview-empty.png
  docs/assets/cluster-overview-new-cluster-creating.png
  docs/assets/cluster-overview-new-cluster-healthy.png
  docs/assets/contact-feedback-and-support.png
  docs/assets/early-access-paid-request.png
  docs/assets/early-access-reserved-clusters-edit.png
  docs/assets/early-access-reserved-clusters-overview.png
Labels: size/XS

#38 new client-view
  docs/assets/cluster-detail-clients.png
  docs/assets/cluster-details-client-details.png
  docs/assets/cluster-details-create-client.png
  docs/gettingstarted_quick-start.md
Labels: size/XS

#39 Add Java and Kotlin, restructure
  .prettierrc
  docs/assets/getting-started-java-thumbnail.png
  docs/assets/getting-started-kotlin-thumbnail.png
  docs/connectzeebe_build-your-own-client.md
  docs/connectzeebe_cli-zbctl.md
  docs/connectzeebe_go-client.md
  docs/connectzeebe_java-client.md
  docs/connectzeebe_java-spring.md
  docs/connectzeebe_kotlin-spring.md
  docs/connectzeebe_node-client.md
  docs/connectzeebe_other-clients.md
  docs/gettingstarted_overview.md
  docs/gettingstarted_quick-start-advanced.md
  docs/gettingstarted_quick-start.md
  docs/welcome.md
  website/pages/en/index.js
  website/sidebars.json
Labels: size/XXL

#41 Add C# ASP.Net Getting Started Guide
  docs/assets/getting-started-aspnet-thumbnail.png
  docs/connectzeebe_aspnet-csharp.md
  website/sidebars.json
Labels: size/XL

#42 update babel
  website/package-lock.json
Labels: lgtm, size/XXL

#43 HOLD Added docs for org settings
  docs/assets/avatar-menue-multiple-organisations.png
  docs/assets/avatar-menue.png
  docs/assets/early-access-reserved-clusters-edit.png
  docs/assets/early-access-reserved-clusters-overview.png
  docs/gettingstarted_camunda-cloud-console.md
  docs/professional_reservations.md
  website/package-lock.json
Labels: size/XL
